limit_req_zone $binary_remote_addr zone=yilin:10m rate=20r/m;

server {
    server_name yilin.alsun.top;

    location / {
        limit_req zone=yilin burst=3 nodelay;
        proxy_pass http://127.0.0.1:8666;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /fonts/ { proxy_pass http://127.0.0.1:8666; proxy_set_header Host $host; }
    location /images/ { proxy_pass http://127.0.0.1:8666; proxy_set_header Host $host; }
    location /_next/ {
        proxy_pass http://127.0.0.1:8666;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    location /downloads/ { proxy_pass http://127.0.0.1:8666; proxy_set_header Host $host; }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/nginx/ssl/yilin/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/yilin/privkey.pem;
}

server {
    if ($host = yilin.alsun.top) { return 301 https://$host$request_uri; }
    listen 80;
    listen [::]:80;
    server_name yilin.alsun.top;
    return 404;
}
